# Generated by Django 5.1.3 on 2024-11-21 05:28

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=user.utils.create_directory_path),
        ),
    ]
